### ISSUE TITLE
Add a feature for Searching the books

### ISSUE THREAD

**Issue by FSfarhaan** [FSfarhaan/Library-Website#1]
Add a feature that can allow users to search the book if it is available in the library or not.

**Comment by aryankshl** [comment]
hey @FSfarhaan can you assign this to me?

**Comment by aryankshl** [comment]
hey @FSfarhaan I have made PR related to the same can you check and accept it? 
![search bar](https://github.com/FSfarhaan/Library-Website/assets/98872365/296129be-962d-4317-890e-6e97bb0e1aab)

**Comment by aryankshl** [comment]
And please first assign me too.

**Comment by FSfarhaan** [comment]
> hey @FSfarhaan I have made PR related to the same can you check and accept it? 
> ![search bar](https://github.com/FSfarhaan/Library-Website/assets/98872365/296129be-962d-4317-890e-6e97bb0e1aab)
> 

Thanks for your help, I've merged your pull request 😀
